apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/pepe1az417/apps-repo
  ref:
    branch: main
  secretRef:
    name: apps-repo-auth